const ART = Object.freeze({
    TESBIH_TAM:      { name: "Teşbih (Tam Benzetme)", tooltip: "Aralarında benzerlik bulunan iki şeyden zayıf olanı güçlü olana benzetme; dört öğe tam kullanılır." },
    TESBIH_BELIG:    { name: "Teşbih-i Beliğ",        tooltip: "Yalnızca benzeyen ve kendisine benzetilen ile yapılan, edat ve yön kullanılmayan güzel benzetme." },
    TESBIH:          { name: "Teşbih",                 tooltip: "Aralarında benzerlik ilgisi kurulan iki varlıktan birini diğerine benzetme sanatı." },
    ACIK_ISTIARE:    { name: "Açık İstiare",           tooltip: "Kendisine benzetilen söylenip benzeyen söylenmeden yapılan eğretileme." },
    KAPALI_ISTIARE:  { name: "Kapalı İstiare",         tooltip: "Benzeyen söylenip kendisine benzetilen söylenmeden yapılan eğretileme." },
    MECAZI_MURSEL:   { name: "Mecaz-ı Mürsel",         tooltip: "Benzetme amacı gütmeden, parça-bütün, iç-dış, neden-sonuç gibi ilgilerle sözcüğü başka anlamda kullanma." },
    KINAYE:          { name: "Kinaye",                  tooltip: "Bir sözün hem gerçek hem mecaz anlamını düşündürecek biçimde kullanılması; asıl kastedilen mecaz anlamdır." },
    TESHIS:          { name: "Teşhis",                  tooltip: "İnsan dışındaki varlıklara insana özgü nitelikler kazandırma, kişileştirme." },
    INTAK:           { name: "İntak",                   tooltip: "İnsan dışındaki varlıkları konuşturma sanatı; her intakta teşhis de vardır." },
    TARIZ:           { name: "Tariz",                   tooltip: "Söylenen sözün tam tersini kastederek iğneleme, alay etme sanatı." },
    TENASUP:         { name: "Tenasüp",                 tooltip: "Anlamca birbiriyle ilişkili, aynı anlam alanına ait sözcükleri bir arada kullanma." },
    TEVRIYE:         { name: "Tevriye",                 tooltip: "Birden fazla gerçek anlamı olan sözcüğü uzak anlamı kastedilerek kullanma." },
    TECAHUL:         { name: "Tecahül-i Arif",          tooltip: "Bilinen bir gerçeği, bir nükteye dayanarak bilmiyormuş gibi söyleme." },
    HUSNI_TALIL:     { name: "Hüsn-i Talil",            tooltip: "Doğal bir olayın gerçek nedenini bir yana bırakıp güzel ve hayali bir nedene bağlama." },
    TEZAT:           { name: "Tezat",                   tooltip: "Karşıt anlamlı kavramları bir arada kullanarak anlamı güçlendirme." },
    LEFF_U_NESR:     { name: "Leff ü Neşr",             tooltip: "Birkaç kavramı sıraladıktan sonra bunlara karşılık gelen kavramları belli düzenle anlatma." },
    TELMIH:          { name: "Telmih",                  tooltip: "Herkesçe bilinen bir olay, kişi veya hikâyeyi çağrıştırma, hatırlatma." },
    MUBALAGA:        { name: "Mübalağa",                tooltip: "Bir şeyi olduğundan çok daha büyük veya küçük gösterme, abartma." },
    TEKRIR:          { name: "Tekrir",                  tooltip: "Anlamı güçlendirmek için aynı sözcük veya söz grubunu yineleme." },
    NIDA:            { name: "Nida",                    tooltip: "Ünlem sözcükleriyle coşkulu seslenme yapma sanatı." },
    ISTIFHAM:        { name: "İstifham",                tooltip: "Cevap beklemeden, duyguyu etkili kılmak için soru biçiminde anlatma." },
    RUCU:            { name: "Rücu",                    tooltip: "Söylenen sözden caymış gibi görünüp düşünceyi daha güçlü biçimde geliştirme." },
    TERDID:          { name: "Terdid",                  tooltip: "Bir düşünceyi beklenmedik biçimde sonuçlandırarak okuyucuyu şaşırtma." },
    AKIS:            { name: "Akis",                    tooltip: "Cümledeki söz sırasını ters çevirerek tekrarlama, söz simetrisi kurma." },
    SEHLI_MUMTENI:   { name: "Sehl-i Mümteni",          tooltip: "Kolay gibi görünen ama benzeri söylenmeye çalışıldığında zorluğu anlaşılan yalın ifade." },
    KATI:            { name: "Kat'ı",                   tooltip: "Anlamı güçlendirmek için sözü yarıda kesme sanatı." },
    CINAS:           { name: "Cinas",                   tooltip: "Sesleri aynı anlamları farklı sözcükleri bir arada kullanma." },
    ALITERASYON:     { name: "Aliterasyon",             tooltip: "Aynı ses veya hecenin tekrarıyla ahenk ve ses güzelliği yaratma." },
    SECI:            { name: "Seci",                    tooltip: "Düzyazıda cümle sonlarında uyak yapma, nesrin kafiyesi." },
    IRSAL_I_MESEL:   { name: "İrsal-i Mesel",           tooltip: "Konuya uygun atasözü veya özlü söz kullanarak düşünceyi destekleme." },
});

const DATA = Object.freeze([

  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Ali arslan gibi cesurdur.", hint:"Dört öğe tam: Ali (benzeyen), arslan (kendisine benzetilen), gibi (edat), cesur (yön)." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Cennet gibi güzel vatanımız.", hint:"Benzetilen (vatan), kendisine benzetilen (cennet), edat (gibi), yön (güzel)." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Atlılar geçmişti rüzgâr misali akan coşkun nehirden.", hint:"'Misali' benzetme edatı. Atlılar rüzgâra benzetilmiş." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Yüzü ay gibi parlaktı.", hint:"Yüz (benzeyen), ay (kendisine benzetilen), gibi (edat), parlak (yön)." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Ok gibi fırladı yerinden.", hint:"Hızlı kalkma oka benzetilmiş, 'gibi' edatı kullanılmış." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Gözleri deniz gibi derindi.", hint:"Gözlerin derinliği denize benzetilmiş, edat ve yön mevcut." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Suyu billur gibi berraktı.", hint:"Suyun berraklığı billura benzetilmiş." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Servi gibi salınır nazlı güzel.", hint:"Güzelin salınışı serviye benzetilmiş, 'gibi' edatı var." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Kömür gibi siyah gözlerin mi var, hilâl gibi düzgün kaşların mı var?", hint:"Gözler kömüre, kaşlar hilâle benzetilmiş. 'Gibi' edatı ile iki ayrı tam benzetme." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Tilki gibi kurnazdı.", hint:"Kurnazlık tilkiye benzetilmiş, edat (gibi) ve yön (kurnaz) mevcut." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Çita gibi hızlı koşuyordu.", hint:"Hızlı koşma çitaya benzetilmiş." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Pamuk gibi yumuşak elleri vardı.", hint:"Ellerin yumuşaklığı pamuğa benzetilmiş." },

  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Gördüm deniz dedikleri bin başlı ejderi.", hint:"Benzeyen (deniz) ve kendisine benzetilen (ejder) var; edat ve yön yok." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Gider oldum kömür gözlüm elveda.", hint:"Göz kömüre benzetilmiş. Edat ve yön yok." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Altın başaklar tarlada dalgalanıyordu.", hint:"Başaklar altına benzetilmiş; edat ve yön kullanılmamış." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Cennet vatan.", hint:"Vatan cennete benzetilmiş, sadece iki temel öğe var." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Aşk bir yangındır içimde.", hint:"Aşk yangına benzetilmiş, edat ve yön yok." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Ömrüm bir rüzgârdı, geçti.", hint:"Ömür rüzgâra benzetilmiş, sadece temel öğeler." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Sözlerin zehirdi.", hint:"Sözlerin etkisi zehire benzetilmiş." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Yüreğim yangın yeri.", hint:"Yüreğin acısı yangın yerine benzetilmiş." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Zaman bir nehirdir akıp gider.", hint:"Zamanın akışı nehre benzetilmiş, edat yok." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Hasret bir denizdir.", hint:"Hasretin derinliği ve büyüklüğü denize benzetilmiş." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Hayat bir sınavdır.", hint:"Hayatın zorluğu sınava benzetilmiş." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"İnci dişler, gonca dudaklar.", hint:"Dişler inciye, dudaklar goncaya benzetilmiş. Edat ve yön yok." },

  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Kurban olam kurban olam\nBeşikte yatan kuzuya.", hint:"Bebek (benzeyen) söylenmemiş, kuzu (kendisine benzetilen) söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Şakaklarıma kar mı yağdı ne var?", hint:"Ak saçlar söylenmemiş, kar (kendisine benzetilen) söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Ağaçlar sonbaharda elbiselerini soyundu.", hint:"Yapraklar söylenmemiş, 'elbise' söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Gündüzüm gece oldu.", hint:"Umutsuzluk söylenmemiş, gece (kendisine benzetilen) söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Hilâl kaşlarına hayranım.", hint:"Kaş (benzeyen) söylenmemiş, hilâl (kendisine benzetilen) söylenmiş — mazmun." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"O bir derya idi, enginlere sığmazdı.", hint:"Bilgili/derin kişi söylenmemiş, derya söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Yüreğimde bir volkan patladı.", hint:"Şiddetli öfke/duygu söylenmemiş, volkan söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Baykuş öttü yine gönül evimde.", hint:"Umutsuzluk/kötü haber söylenmemiş, baykuş söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"İnci dişlerini gösterdi gülünce.", hint:"Diş (benzeyen) söylenmemiş, inci söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Serviler salınırdı bahçede.", hint:"Uzun boylu güzeller söylenmemiş, servi söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Ateş düştü yüreğime.", hint:"Acı/ıstırap söylenmemiş, ateş söylenmiş." },

  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Ufukta günün boynu büküldü.", hint:"Güneş (benzeyen) söylenmiş, insan (kendisine benzetilen) söylenmemiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Ali kükreyerek düşmanın üstüne yürüdü.", hint:"Ali söylenmiş, aslan söylenmemiş. Kükreme özelliğinden çıkarılıyor." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Tekerlekler yollara bir şeyler anlatıyor.", hint:"Tekerlekler söylenmiş, insan söylenmemiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Can kafeste durmaz uçar.", hint:"Can söylenmiş, kuş söylenmemiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Gecenin saçları uzadı yine.", hint:"Gece söylenmiş ama karanlığın uzun kadın saçlarına benzetilmesi — insan söylenmemiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Umut çiçek açtı kalbimde.", hint:"Umut söylenmiş, bitki/ağaç söylenmemiş. Çiçek açma özelliğinden çıkarılıyor." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Güneş gülüyor dünyaya.", hint:"Güneş söylenmiş, insan söylenmemiş. Gülme insana özgü." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Rüzgâr fısıldadı adını.", hint:"Rüzgâr söylenmiş, insan söylenmemiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Deniz hırçınlaştı birden.", hint:"Deniz söylenmiş, insan söylenmemiş. Hırçınlaşmak insani bir özellik." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Kirpiklerin ok olmuş sineme saplandı.", hint:"Kirpikler söylenmiş, ok söylenmemiş ama saplamak özelliğiyle ima edilmiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Eşcâr-ı bâğ hırka-i tecrîde girdiler.", hint:"Ağaçlar söylenmiş, derviş söylenmemiş. Yaprak dökme dervişin hırkasını çıkarmasına benzetilmiş." },

  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Halit Ziya'yı okudun mu?", hint:"Yazar adı söylenerek eserleri kastedilmiş — sanatçı-yapıt ilgisi." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Sobayı yaktım.", hint:"Dış (soba) söylenerek iç (odun, kömür) kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Ankara bu karara sıcak bakmıyor.", hint:"Yer adı söylenerek yetkililer kastedilmiş — yer-insan ilgisi." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Ayağını giy.", hint:"Ayak söylenerek ayakkabı kastedilmiş — iç-dış ilgisi." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Dalgalan sen de şafaklar gibi ey nazlı hilâl!", hint:"Hilâl söylenerek bayrak kastedilmiş — parça-bütün ilgisi." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Sana benim gözümle bakan gözler kör olsun.", hint:"Gözler söylenerek insanın bütünü kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Bütün sınıf ayağa kalktı.", hint:"Sınıf (mekân) söylenerek öğrenciler kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"İstanbul'u dinliyorum gözlerim kapalı.", hint:"İstanbul söylenerek oradaki hayat kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Tabağını bitir.", hint:"Tabak (dış) söylenerek yemek (iç) kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Bir bardak su alabilir miyim?", hint:"Bardak (kap) söylenerek içindeki su kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Bütün salon alkışladı.", hint:"Salon (mekân) söylenerek seyirciler kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Ocağımız tütsün daima.", hint:"Ocak söylenerek aile/yuva kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Üç gündür bereket yağıyor.", hint:"Bereket (sonuç) söylenerek yağmur (sebep) kastedilmiş — neden-sonuç ilgisi." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Ünlü raketler Avrupa'dan döndüler.", hint:"Raket (alet) söylenerek tenisçiler kastedilmiş." },

  { cat:"mecaz", answer:ART.KINAYE, text:"Ey benim sarı tamburam\nSen ne için inilersin\nİçim oyuk, derdim büyük.", hint:"'İçim oyuk' hem gerçek (tamburun içi boş) hem mecaz (acılı). Asıl kastedilen mecaz." },
  { cat:"mecaz", answer:ART.KINAYE, text:"O adamın her zaman kapısı açıktır.", hint:"'Kapısı açık' hem gerçek hem mecaz (konuksever)." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Şu karşıma göğüs geren\nTaş bağırlı dağlar mısın.", hint:"'Taş bağırlı' hem gerçek (dağ taştan) hem mecaz (acımasız)." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Ağır ol da molla desinler.", hint:"'Ağır ol' hem gerçek (tartıda ağır) hem mecaz (vakur davran)." },
  { cat:"mecaz", answer:ART.KINAYE, text:"O kadar eli açık ki kimseyi geri çevirmez.", hint:"'Eli açık' hem gerçek hem mecaz (cömert)." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Adamın ağzından bal damlıyor.", hint:"'Ağzından bal damlamak' hem gerçek düşünülebilir hem de mecaz (tatlı dilli)." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Senin gibi dostu olanın düşmana ihtiyacı yok.", hint:"Hem gerçek (dost) hem mecaz (aslında düşmanlık eden). Asıl kastedilen mecaz." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Ayağını denk al.", hint:"Hem gerçek (ayakları dengeli basma) hem mecaz (dikkatli olma)." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Senden iyisi mezarda.", hint:"Hem gerçek düşünülebilir hem mecaz (beğenmeme/eleştiri)." },

  { cat:"mecaz", answer:ART.TESHIS, text:"Bulutlar gözyaşı döktüler.", hint:"Bulutlara 'gözyaşı dökme' gibi insani özellik verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Yapraklar hüzünle yere düşüyordu.", hint:"Yapraklara 'hüzün' gibi insani duygu yüklenmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Güneş öfkeyle baktı dünyaya.", hint:"Güneşe 'öfkeyle bakmak' gibi insani davranış atfedilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Yüce dağlar birbirine göz eder\nRüzgâr ile mektuplaşır, naz eder.", hint:"Dağlara göz etme, naz etme; rüzgâra mektuplaşma verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Ağaçlar fısıldıyordu rüzgârda.", hint:"Ağaçlara fısıldamak gibi insani özellik verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Toprak sevgiyle kucakladı tohumu.", hint:"Toprağa sevgiyle kucaklamak gibi insani davranış verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Şehir uyuyordu sessizce.", hint:"Şehre uyumak gibi insani özellik verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Kalemim ağlıyor bu gece.", hint:"Kaleme ağlamak gibi insani özellik verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Yıldızlar göz kırpıyordu gökyüzünde.", hint:"Yıldızlara göz kırpmak gibi insani davranış verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Rüzgâr şarkı söylüyordu dallarda.", hint:"Rüzgâra şarkı söylemek gibi insani yetenek verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Deniz hırçınlaştı birden.", hint:"Denize hırçınlaşmak gibi insani karakter verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Salındı bahçeye girdi\nÇiçekler selâma durdu.", hint:"Çiçeklere selâma durmak gibi insani davranış verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Mor menekşe boyun eğdi\nGül kızardı hicâbından.", hint:"Menekşeye boyun eğme, güle utanıp kızarma verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Dağlar sırtlarından kürklerini attılar.", hint:"Dağlara kürk çıkarma gibi insani davranış verilmiş (karların erimesi)." },

  { cat:"mecaz", answer:ART.INTAK, text:"Bülbül, 'Senin nazını çekemem' diyordu güle.", hint:"Bülbül hem kişileştirilmiş hem konuşturulmuş. Her intakta teşhis vardır." },
  { cat:"mecaz", answer:ART.INTAK, text:"Güğüm bir gün testiye: 'Yola çıkalım' dedi. Testi: 'Korkarım' dedi.", hint:"İnsan dışı varlıklar konuşturulmuş." },
  { cat:"mecaz", answer:ART.INTAK, text:"Leylek dedi ki: 'Bahar geldi artık!'", hint:"Hayvan konuşturulmuş — intak." },
  { cat:"mecaz", answer:ART.INTAK, text:"Dere dedi ki: 'Ben durmadan akarım.'", hint:"Doğa varlığı konuşturulmuş." },
  { cat:"mecaz", answer:ART.INTAK, text:"Tilki dedi ki: 'Kurnazlık benim işim.'", hint:"Hayvan konuşturulmuş — fabllarda sık kullanılır." },
  { cat:"mecaz", answer:ART.INTAK, text:"Gül konuştu bülbüle, aşkını anlattı.", hint:"Bitki konuşturulmuş." },
  { cat:"mecaz", answer:ART.INTAK, text:"Ağaç dedi ki: 'Köklerim toprağa bağlı, gidemem.'", hint:"Bitki konuşturulmuş." },
  { cat:"mecaz", answer:ART.INTAK, text:"Mor menekşe: 'Bana dokunma' diye bağırdı.", hint:"Bitki konuşturulmuş." },

  { cat:"mecaz", answer:ART.TARIZ, text:"Bu ne kudret ki elifbayı okur ezberden.", hint:"Eşref, cahilliği övüyormuş gibi iğneliyor — söylenenin tam tersi kastediliyor." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Bir yetim görünce döktür dişini\nBozmaya çabala halkın işini\nBir yaralı sarmak için yeltenme.", hint:"Öğüt verir gibi görünüp tam tersini kastediyor." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Her gün geç kalan öğrenciye 'Ne kadar da dakiksin!' demek.", hint:"Söylenen (dakik) ile kastedilen (geç kalan) tam zıt." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Sen ne kadar da zekisin, bütün soruları yanlış yaptın!", hint:"Alaycı biçimde zeki olmadığını belirtme." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Çok cömertsin, değil mi? Bir kuruş bile vermedin.", hint:"Cömert olmadığı halde cömertmiş gibi söylemek." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Ne kadar da kibarsın, kapıyı yüzüme kapattın!", hint:"Kibar olmadığı halde kibarmış gibi iğnelemek." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Sınıfı berbat eden çocuğa 'Maşallah, ne kadar tertipli bir çocuksun!' demek.", hint:"Söylenen (tertipli) ile kastedilen (dağınık) birbirinin zıddı." },


  { cat:"anlam", answer:ART.TENASUP, text:"Yine bahar geldi, bülbül sesinden\nSada verip seslendi mi yaylalar\nÇevre yanın lale sümbül bürümüş.", hint:"Bahar, bülbül, lale, sümbül — anlamca ilişkili sözcükler bir arada." },
  { cat:"anlam", answer:ART.TENASUP, text:"Ayet ayet, sure sure Kur'an okuyup minareden ezan verdi müezzin.", hint:"Ayet, sure, Kur'an, minare, ezan, müezzin — din alanına ait sözcükler." },
  { cat:"anlam", answer:ART.TENASUP, text:"Deli eder insanı bu dünya\nBu gece, bu yıldızlar, bu koku.", hint:"Gece, yıldızlar, koku — anlamca ilişkili sözcükler." },
  { cat:"anlam", answer:ART.TENASUP, text:"Kılıç, kalkan, mızrak savaş meydanını doldurdu.", hint:"Savaş aletleri bir arada kullanılmış." },
  { cat:"anlam", answer:ART.TENASUP, text:"Ay, yıldız, gece gökyüzünde buluştu.", hint:"Gökyüzünü çağrıştıran sözcükler bir arada." },
  { cat:"anlam", answer:ART.TENASUP, text:"Türkü, şarkı, müzik ruhun gıdasıdır.", hint:"Müziği çağrıştıran sözcükler bir arada." },
  { cat:"anlam", answer:ART.TENASUP, text:"Gül, lale, sümbül açmış bahçede.", hint:"Çiçek isimleri bir arada — aynı anlam alanına ait." },
  { cat:"anlam", answer:ART.TENASUP, text:"Deniz, kum, güneş ne güzel bir üçlü.", hint:"Yaz/tatili çağrıştıran sözcükler bir arada." },

  { cat:"anlam", answer:ART.TEVRIYE, text:"Gül yağını eller sürünür, çatlasa bülbül.", hint:"'El' hem organ hem 'yabancı' anlamında — iki gerçek anlam. Uzak anlam kastedilmiş." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Bu kadar letafet çünkü sende var\nBeyaz gerdanında bir de ben gerek.", hint:"'Ben' hem deri üzerindeki nokta hem birinci kişi zamiri. İki anlam da gerçek." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Bâkî kalan bu kubbede bir hoş sadâ imiş.", hint:"'Bâkî' hem şairin adı hem 'kalıcı, ebedî'. İki gerçek anlam." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Havada yaprağa döndürdü rüzgâr beni.", hint:"'Rüzgâr' hem yel hem zaman. İki gerçek anlam, uzak olan kastedilmiş." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Bana Tahir Efendi kelp demiş\nİtikadımca kelp tahirdir.", hint:"'Tahir' hem kişi adı hem 'temiz' anlamında. İki gerçek anlam." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Gül gülse daim, ağlasa bülbül aceb değil\nZira kimine ağla demişler, kimine gül.", hint:"'Gül' hem çiçek hem gülme eylemi — iki gerçek anlam." },

  { cat:"anlam", answer:ART.TECAHUL, text:"Gökyüzünün başka rengi de varmış\nGeç fark ettim taşın sert olduğunu\nSu insanı boğar, ateş yakarmış.", hint:"Bilinen gerçekler bilmezden gelinip güzel bir nükteye bağlanmış." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Ey şuh, Nedim'le bir seyrin işittik\nTenhaca varıp Göksu'ya işret var içinde.", hint:"Eğlendiğini bildiği halde bilmiyormuş gibi davranıyor." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Gökyüzünde parlayan o nedir? Güneş mi, senin yüzün mü?", hint:"Güneşin ne olduğu bilindiği halde sevgiliyi yüceltmek için bilmezden geliniyor." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Şakaklarıma kar mı yağdı ne var?", hint:"Saçların ağardığını bildiği halde 'kar mı yağdı' diye sorması." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Bana kara diyen dilber, gözlerin kara değil mi?", hint:"Gözlerinin kara olduğunu bilerek bilmezden gelme." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Kim bu cennet vatanın uğruna olmaz ki feda?", hint:"Herkesin feda olacağını bilerek soru sorma." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Göz gördü gönül sevdi, nedir bu halim?", hint:"Aşığın halini bildiği halde bilmezden gelmesi." },

  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Güzel şeyler düşünelim diye\nYemyeşil oluvermiş ağaçlar.", hint:"Yeşilliğin doğal nedeni yerine güzel bir neden gösterilmiş." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Gül kızardı hicabından (utancından).", hint:"Güllerin kırmızı olması doğaldır; şair bunu utanmaya bağlıyor." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Birçok gidenin her biri memnun ki yerinden\nBirçok seneler geçti dönen yok seferinden.", hint:"Ölenlerin dönmeyişi yerlerinden memnun olmalarına bağlanıyor." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Senin o gül yüzünü görmek için güneş her sabah doğuyor.", hint:"Güneşin doğması doğal; şair bunu sevgiliye bağlıyor." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Ey sevgili sen bu ilden gideli\nYaprak döktü ağaçlar, coştu gökyüzü.", hint:"Yaprak dökülmesi doğal; sevgilinin gidişine bağlanmış." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Güneş, seni görünce daha parlak doğar.", hint:"Güneşin parlaklığı sevgiliye bağlanmış." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Çiçekler, senin güzelliğini kıskandıkları için açıyor.", hint:"Çiçeklerin açması doğal; şair bunu kıskançlığa bağlıyor." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Kuşlar, senin sesini duymak için ötüyor.", hint:"Kuşların ötmesi doğal; sevgilinin sesine bağlanmış." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Yağmur, senin ayrılığına ağlıyor.", hint:"Yağmurun yağması doğal; ayrılığa bağlanmış." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Saksında ruhumun bütün yası var\nDerdimle soluyor açılan gonca.", hint:"Goncanın solması doğal; şair bunu dert çekmeye bağlıyor." },

  { cat:"anlam", answer:ART.TEZAT, text:"Neden böyle düşman görünürsünüz\nYıllar yılı dost bildiğim aynalar?", hint:"'Dost' ve 'düşman' karşıt kavramlar bir arada." },
  { cat:"anlam", answer:ART.TEZAT, text:"Ağlarım hatıra geldikçe gülüştüklerimiz.", hint:"'Ağlamak' ve 'gülüşmek' zıt sözcükler." },
  { cat:"anlam", answer:ART.TEZAT, text:"Güvenme varlığa düşersin darlığa.", hint:"'Varlık' ve 'darlık' karşıt kavramlar." },
  { cat:"anlam", answer:ART.TEZAT, text:"Çın çın ötüyor sessizlik.", hint:"'Sessizlik' ve 'çın çın ötmek' karşıt." },
  { cat:"anlam", answer:ART.TEZAT, text:"Kuru idik yaş olduk, ayağ idik baş olduk.", hint:"Kuru-yaş, ayak-baş zıt kavramlar." },
  { cat:"anlam", answer:ART.TEZAT, text:"Aşk hem cennet hem cehennem.", hint:"Cennet ve cehennem karşıt kavramlar bir arada." },
  { cat:"anlam", answer:ART.TEZAT, text:"Acı tatlı hatıralar.", hint:"Acı ve tatlı karşıt kavramlar bir arada." },
  { cat:"anlam", answer:ART.TEZAT, text:"Savaş barış getirmez.", hint:"Savaş ve barış karşıt kavramlar." },
  { cat:"anlam", answer:ART.TEZAT, text:"Zengin fakir aynı topraktan.", hint:"Zengin ve fakir zıt kavramlar." },
  { cat:"anlam", answer:ART.TEZAT, text:"Geceler uzun, gündüzler kısa.", hint:"Uzun-kısa, gece-gündüz zıt kavramlar." },

  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Bahçıvan güller ekmiş\nDikeniyle bahçeye.", hint:"Bahçıvan→bahçe, gül→diken sıralı eşleştirme." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Gönlümü, aklımı, sabrımı aldın\nDeli ettin, şaşırttın, ağlattın.", hint:"Gönül→deli, akıl→şaşırt, sabır→ağlat — düzenli eşleştirme." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Göz, kaş, kirpik; kara, yay, ok.", hint:"Göz→kara, kaş→yay, kirpik→ok sıralı eşleştirme." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Baran değil, şafak değil, ebr-i seher değil\nGözyaşıdır, ciğer kanıdır, dûd-ı âhtır.", hint:"Baran→gözyaşı, şafak→ciğer kanı, ebr→dûd-ı âh sıralı eşleştirme." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Buy-i gül taktir olunmuş, nazın işlenmiş ucu\nBiri olmuş hoy birisi dest-mal olmuş sana.", hint:"Gül kokusu→ter, naz→mendil eşleştirmesi." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Deniz, kum, güneş; mavi, sarı, sıcak.", hint:"Deniz→mavi, kum→sarı, güneş→sıcak sıralı eşleştirme." },

  { cat:"anlam", answer:ART.TELMIH, text:"Vefasız Aslı'ya yol gösteren bu\nKerem'in sazına cevap veren bu.", hint:"Kerem ile Aslı hikâyesi çağrıştırılıyor." },
  { cat:"anlam", answer:ART.TELMIH, text:"Gökyüzünde İsa ile\nTur Dağı'nda Musa ile\nElindeki asa ile.", hint:"Hz. İsa ve Hz. Musa'nın olayları hatırlatılıyor." },
  { cat:"anlam", answer:ART.TELMIH, text:"Ekmekten, sudan ayrı, Mecnun gibi yalnız yaşıyordu.", hint:"Leylâ ile Mecnun'a gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Ne büyüksün ki kanın kurtarıyor Tevhid'i\nBedrin aslanları ancak bu kadar şanlı idi.", hint:"Bedir Savaşı'na telmih." },
  { cat:"anlam", answer:ART.TELMIH, text:"Ferhat gibi dağları delerim senin için.", hint:"Ferhat ile Şirin hikâyesine gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Yusuf gibi güzelsin.", hint:"Hz. Yusuf'un güzelliğine gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Nuh gibi tufandan kurtulmak istiyorum.", hint:"Nuh Tufanı'na gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"İbrahim gibi ateşe atılsa da vazgeçmem.", hint:"Hz. İbrahim'in ateşe atılmasına gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Musa gibi denizi yararım senin için.", hint:"Hz. Musa'nın denizi yarmasına gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Ömer gibi adaletli olmalıyız.", hint:"Hz. Ömer'in adaletine gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Od'a gireyim Mevlâ.", hint:"Hz. İbrahim'in ateşe atılma olayına gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Seretti hava üzre denir taht-ı Süleyman\nOl saltanatın yeller eser şimdi yerinde.", hint:"Süleyman Peygamber'in saltanatına gönderme." },

  { cat:"anlam", answer:ART.MUBALAGA, text:"Bir ah çeksem dağı taşı eritir\nGözüm yaşı değirmeni yürütür.", hint:"Ahla dağ eritme, gözyaşıyla değirmen döndürme — abartı." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Kırk gün oldu kaynatırım kaynamaz.", hint:"Kazın pişmemesi — olağanüstü abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Sana dar gelmeyecek makberi kimler kazsın\nGömelim gel seni tarihe desem sığmazsın.", hint:"Tarihe sığmamak — büyüklük abartılmış." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Ağladım ağladım, gözyaşlarım sel olup aktı.", hint:"Gözyaşlarının sel olması — abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Dünya kadar derdim var.", hint:"Dertlerin dünya kadar büyük olması — abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Ağlamaktan gözümde yaş kalmadı.", hint:"Gözde yaş kalmaması — abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"O kadar hızlı koştu ki ışık hızıyla yarıştı.", hint:"Koşma hızının ışık hızıyla karşılaştırılması — abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Âhımdan bir şerare düşse âsumana\nYakardı âlemi ser-tâ-be-pây.", hint:"Ahın gökyüzüne düşüp tüm dünyayı yakması — abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Nice ağladım ki gözümden akan sular\nYedi deryayı geçip ummana karıştı.", hint:"Gözyaşının yedi denizi geçmesi — abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Ak gerdanında benler öldürdü beni.", hint:"Benlerin şairi öldürmesi — abartma." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Ölüm indirmede gökler, ölü püskürmede yer.", hint:"Göklerin ölüm indirmesi, yerin ölü püskürmesi — savaş abartılmış." },

  { cat:"anlam", answer:ART.TEKRIR, text:"Vur, aşkın ve Hak'kın zaferi için\nVur, senden bak dünya bunu istiyor.", hint:"'Vur' tekrarlanarak anlam güçlendirilmiş." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Kaldırımlar ıstırap çekenlerin annesi\nKaldırımlar içimde yaşamış bir insandır.", hint:"'Kaldırımlar' her dize başında yineleniyor." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Dedim inci nedir dedi dişimdir\nDedim kalem nedir dedi kaşımdır.", hint:"'Dedim, dedi' tekrarıyla tekrir yapılmış." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Gel ey sevgili, gel ey sevgili, gel ey sevgili.", hint:"'Gel ey sevgili' tekrarı hasreti vurguluyor." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Ağlama gözlerim ağlama\nDayanamam ben bu acıya\nAğlama gözlerim ağlama.", hint:"'Ağlama gözlerim ağlama' tekrarı çaresizliği vurguluyor." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Gitme, gitme ne olursun\nKal biraz daha yanımda\nGitme, gitme ne olursun.", hint:"'Gitme' tekrarı yalvarışı güçlendiriyor." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Gül gül dedi bülbül güle\nGül gülmedi gitti.", hint:"'Gül' sözcüğünün tekrarıyla anlam derinleşiyor." },

  { cat:"anlam", answer:ART.NIDA, text:"Sen ey Kars'lar, Antep'ler, Erzurum'lar, Maraş'lar!", hint:"'Ey' ünlemiyle coşkulu seslenme." },
  { cat:"anlam", answer:ART.NIDA, text:"Ey mavi göklerin beyaz ve kızıl süsü!", hint:"'Ey' ünlemiyle bayrağa seslenilmiş." },
  { cat:"anlam", answer:ART.NIDA, text:"Ey benim bahtiyar gönlüm!", hint:"'Ey' ünlemiyle gönle seslenme." },
  { cat:"anlam", answer:ART.NIDA, text:"Ah, nerede o eski günler!", hint:"'Ah' ünlemiyle özlem ifade edilmiş." },
  { cat:"anlam", answer:ART.NIDA, text:"Eyvah, gençliğim elden gitti!", hint:"'Eyvah' ünlemiyle pişmanlık dile getirilmiş." },
  { cat:"anlam", answer:ART.NIDA, text:"Yâ Rab, bu nasıl bir dert!", hint:"'Yâ Rab' ile Allah'a seslenilmiş." },
  { cat:"anlam", answer:ART.NIDA, text:"Ey felek, ne ettin bana!", hint:"'Ey' ünlemiyle feleğe sitem." },
  { cat:"anlam", answer:ART.NIDA, text:"Ey Türk gençliği! Birinci vazifen Türk istiklâlini korumaktır.", hint:"'Ey' ünlemiyle Türk gençliğine seslenme." },

  { cat:"anlam", answer:ART.ISTIFHAM, text:"Beni candan usandırdı, cefadan yâr usanmaz mı?\nFelekler yandı ahımdan, muradım şem'i yanmaz mı?", hint:"Cevap beklemeden soru biçiminde duygu aktarılmış." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Ben de mi böyle uykusuz kalacaktım\nSessiz, sedasız mı olacaktım böyle?", hint:"Soru sormak değil, duyguyu etkili kılmak amaçlanmış." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Kim bu cennet vatanın uğruna olmaz ki feda?", hint:"Cevap beklenmeden vatanseverlik pekiştiriliyor." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Bu kadar mıydı aşkımız?", hint:"Soru yoluyla hayal kırıklığı dile getiriliyor." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Neyleyim sensiz baharı?", hint:"Soru yoluyla sensizliğin anlamsızlığı vurgulanıyor." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Neden böyle solgun yüzün?", hint:"Soru yoluyla merak ve endişe dile getiriliyor." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Dertliyim kimseye diyemem, derdimi kime söyleyim?", hint:"Çaresizlik soru yoluyla ifade ediliyor." },

  { cat:"anlam", answer:ART.RUCU, text:"Erbab-ı teşaür çoğalıp şair azaldı\nYok öyle değil, şairin ancak adı kaldı.", hint:"Önceki sözden caymış gibi görünüp düşünceyi geliştiriyor." },
  { cat:"anlam", answer:ART.RUCU, text:"Ferda senin, dedim beni alkışladın\nSenin değil, ferda sana vediadır.", hint:"İlk sözden caymış gibi görünüp daha derin bir anlam veriyor." },
  { cat:"anlam", answer:ART.RUCU, text:"Dedim dilber, dedim ay parçasıdır\nYok yok, güneştir o, nur saçıyor.", hint:"İlk benzetmeden vazgeçip daha güçlü bir ifadeye geçiliyor." },
  { cat:"anlam", answer:ART.RUCU, text:"Sandım ki bir rüzgâr esti geçti\nYok yok, bir fırtınaymış içimi yıkan.", hint:"İlk benzetmeden caynıp daha güçlü bir benzetme yapılıyor." },

  { cat:"anlam", answer:ART.TERDID, text:"Dişin mi ağrıyor? Çek kurtul\nVerem misin? Üzülme\u2026 Ölür gidersin!", hint:"Beklenmedik sonuçla okuyucu şaşırtılıyor." },
  { cat:"anlam", answer:ART.TERDID, text:"Aşk mıdır, sevda mıdır, nedir bu içimdeki\nAnlamadım, çözemedim ben bu karmaşanın.", hint:"Duygunun ne olduğu konusundaki belirsizlik şaşırtıcı biçimde sonlanıyor." },
  { cat:"anlam", answer:ART.TERDID, text:"Kalır mıyım, gider miyim, nedir bu kararım\nVeremedim, bilemedim ben bu ayrılığın.", hint:"Karar verme sürecinde beklenmedik bir sonuca varılıyor." },

  { cat:"anlam", answer:ART.AKIS, text:"Yaşamak için yemeli\nYemek için yaşamamalı.", hint:"Söz sırası tersine çevrilerek tekrarlanmış." },
  { cat:"anlam", answer:ART.AKIS, text:"İzmir'in denizi kız, kızı deniz\nSokakları hem kız, hem deniz kokar.", hint:"'Deniz-kız' sırası 'kız-deniz' olarak tersine çevrilmiş." },
  { cat:"anlam", answer:ART.AKIS, text:"Hayatın gayesi, gaye hayatın.", hint:"Söz sırası ters düzenlenmiş." },
  { cat:"anlam", answer:ART.AKIS, text:"Gül için bülbül ağlar, ağlar bülbül için gül.", hint:"Söz sırası tersine çevrilerek anlam derinleştirilmiş." },

  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Ete kemiğe büründüm\nYunus diye göründüm.", hint:"Kolay gibi görünen ama benzeri söylenemeyecek yalın ifade." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Beni bende demen bende değilim\nBir ben vardır bende benden içeri.", hint:"Sade görünüşlü ama derin anlamlı, benzeri söylenemeyecek güçlü ifade." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"İstanbul'u dinliyorum, gözlerim kapalı.", hint:"Kolay söylenmiş gibi duran ama benzerini söylemenin zor olduğu söz." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Gönül kimi severse güzel odur.", hint:"Yalın ama derin — benzeri söylenemez." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Ben bir Türk'üm, dinim cinsim uludur.", hint:"Sade ama güçlü — kolay gibi görünüp benzeri zor söylenir." },

  { cat:"anlam", answer:ART.KATI, text:"Gün, öylesine güzel ki!\nÖylesine güzel ki dünya\nYaşadıkça\nAkşam öylesine güzel ki!\nÖylesine güzel ki akşamda ay\nAyda kadın\u2026", hint:"Sözün yarıda kesilmesiyle anlam derinleştirilmiş." },
  { cat:"anlam", answer:ART.KATI, text:"Seni sevmek ne güzel şey, ama\u2026", hint:"Söz yarıda kesilerek okuyucunun hayal gücüne bırakılmış." },
  { cat:"anlam", answer:ART.KATI, text:"Aşkınla yandım, kül oldum\nNe fayda, sensiz geçen günler\u2026", hint:"Söz yarıda kesilerek etkili bir sessizlik yaratılmış." },


  { cat:"soz", answer:ART.CINAS, text:"Al beni, ele beni\nKül edip ele beni\nSevdirme ele beni.", hint:"'Ele' farklı anlamlarda: 'elekte elemek' ve 'başkasına'." },
  { cat:"soz", answer:ART.CINAS, text:"Her nefeste eyledik yüz bin günah\nBir günaha etmedik hiçbir gün ah.", hint:"'Günah' ve 'gün ah' sesleri aynı, anlamları farklı." },
  { cat:"soz", answer:ART.CINAS, text:"Kalem böyle çalınmıştır yazıma\nYazım kışa uymaz, kışım yazıma.", hint:"'Yazıma' hem yazı/kader hem yaz mevsimi anlamında." },
  { cat:"soz", answer:ART.CINAS, text:"Kısmetindir gezdiren yer yer seni\nArşa çıksan akıbet yer yer seni.", hint:"İlk 'yer yer' mekânlar; ikinci 'yer' yutmak/gömmek anlamında." },
  { cat:"soz", answer:ART.CINAS, text:"Hey oynayan yavrular\nAğaçta kuş yavrular\nBenim derdim yavrular.", hint:"'Yavrular' üç farklı anlamda: çocuklar, yavrulamak, çoğalmak." },
  { cat:"soz", answer:ART.CINAS, text:"Gül ağacı gül değil\nKoklamaya gül değil.", hint:"'Gül' hem çiçek hem gülme eylemi anlamında." },
  { cat:"soz", answer:ART.CINAS, text:"Niçin kondun a bülbül\nBenim gül dalıma kondun.", hint:"'Konmak' farklı anlamlarda kullanılmış." },
  { cat:"soz", answer:ART.CINAS, text:"El çek tabip el çek yaramdan\nYaramdan el çek ki kanım durulsun.", hint:"'El çekmek' farklı bağlamlarda kullanılmış." },
  { cat:"soz", answer:ART.CINAS, text:"Ey kimsesizler el veriniz kimsesizlere\nOnlardır ancak el verecek kimse sizlere.", hint:"'Kimsesizler' ve 'kimse sizlere' — sesler benzer, anlamlar farklı." },

  { cat:"soz", answer:ART.ALITERASYON, text:"Kargayı kuzgunun kovardı kondurmazdı.", hint:"'K' sesinin tekrarıyla ses güzelliği yaratılmış." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Karşı yatan karlı kara dağlar, kararıptır, otu bitmez.", hint:"'Kar' hecesinin yinelenmesiyle ses ahengi." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Dest-bûsî arzusuyla ölürsem dostlar\nKûze eylen toprağım sunun anınla yâre su.", hint:"'S' sesinin tekrarıyla ahenkli ses düzeni — Fuzuli." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Sessiz gemi şimdi sensiz\u2026", hint:"'S' sesinin tekrarıyla ses ahengi." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Gül goncası gibi gülen yüzün.", hint:"'G' sesinin tekrarıyla ses güzelliği." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Sırma saçlı sevgili.", hint:"'S' sesinin tekrarıyla ses ahengi." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Bir beste besteledim bu bahar.", hint:"'B' sesinin tekrarıyla ses güzelliği." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Eylülde melül oldu gönül, soldu lâle\nBir kaküle meyletti gönül, geldi bu hâle.", hint:"'L' sesinin yoğun tekrarıyla ses ahengi." },

  { cat:"soz", answer:ART.SECI, text:"Alimsin, ilmine gayet yok\nKadirsin, kudretine nihayet yok.", hint:"'Gayet' ve 'nihayet' ile cümle sonlarında uyak — düzyazının kafiyesi." },
  { cat:"soz", answer:ART.SECI, text:"İlahi, kabul senden, red senden; şifa senden, dert senden.", hint:"Cümle sonlarında ses uyumu sağlanmış." },
  { cat:"soz", answer:ART.SECI, text:"At ölür meydan kalır, yiğit ölür şan kalır.", hint:"'Meydan kalır' ve 'şan kalır' ile cümle sonu uyak." },
  { cat:"soz", answer:ART.SECI, text:"Dilde figan, elde aman, gönülde hicran.", hint:"Cümle sonlarındaki ses benzerliği — düzyazı uyağı." },
  { cat:"soz", answer:ART.SECI, text:"Gönlümde hasret, gözümde yaş, dilimde feryat.", hint:"Cümle sonlarındaki yapısal ses uyumu." },
  { cat:"soz", answer:ART.SECI, text:"Gül dalında bülbül öter, gönlümde aşkım tüter.", hint:"'Öter' ve 'tüter' ile cümle sonu uyak." },

  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"'Balık baştan kokar' bunu bilmemek\nSeyranî gafilin ahmaklığından.", hint:"'Balık baştan kokar' atasözü şiir içinde kullanılmış." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Balık baştan kokar derler, inanmıştım bu söze.", hint:"Atasözü düşünceyi desteklemek için kullanılmış." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Ayağını yorganına göre uzat demişler.", hint:"Atasözü konuya uygun biçimde kullanılmış." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Ne demişler, bal bal demekle ağız tatlanmaz.", hint:"Atasözüyle düşünce pekiştirilmiş." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Görünen köy uzakta değildir, demişler.", hint:"Atasözü düşünceyi desteklemek için kullanılmış." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Ağaç yaşken eğilir demişler.", hint:"Atasözü konuya uygun biçimde kullanılmış." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Damlaya damlaya göl olur demişler.", hint:"Atasözüyle sabır ve süreklilik pekiştirilmiş." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"İşleyen demir pas tutmaz demişler.", hint:"Atasözüyle çalışkanlığın önemi vurgulanmış." },


  { cat:"anlam", answer:ART.TEVRIYE, text:"Ulusun korkma, nasıl böyle bir imânı boğar\nMedeniyyet dediğin tek dişi kalmış canavar.", hint:"'Tek dişi kalmış' hem gerçek (yaşlanmış, güçsüz) hem mecaz (son gücü) anlamda." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Her kuşun eti yenmez.", hint:"'Kuş' hem gerçek hayvan hem de 'kişi' anlamında. 'Et' hem gerçek hem 'iş/davranış' anlamında." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Eyleme vaktini zâyi, deme kış geldi yaza.", hint:"'Yaz' hem mevsim hem 'yaz-' eylemi anlamında. İki gerçek anlam." },

  { cat:"anlam", answer:ART.TECAHUL, text:"Bahar geldi mi, yoksa ben mi yanılıyorum?", hint:"Baharın geldiğini bilerek bilmezden gelme." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Bu dünya fanidir, bilmez miyiz?", hint:"Dünyanın fani olduğunu bile bile soru sorma." },
  { cat:"anlam", answer:ART.TECAHUL, text:"Seni öldüren yârin güzelliği mi, senin sevdan mı bilmem.", hint:"Bildiği halde bilmezden gelip soru biçiminde ifade etme." },

  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Anne, baba, çocuk; sevgi, şefkat, neşe.", hint:"Anne→sevgi, baba→şefkat, çocuk→neşe sıralı eşleştirme." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Aşk, sevgi, muhabbet; kalp, ruh, can.", hint:"Aşk→kalp, sevgi→ruh, muhabbet→can sıralı eşleştirme." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Ay, yıldız, gece; parlak, ışıltı, karanlık.", hint:"Ay→parlak, yıldız→ışıltı, gece→karanlık sıralı eşleştirme." },

  { cat:"anlam", answer:ART.AKIS, text:"Para parayı çeker, çeker parayı para.", hint:"Söz sırası tersine çevrilerek tekrarlanmış." },
  { cat:"anlam", answer:ART.AKIS, text:"Aşk imkânsızlıkta gizlidir, imkânsızlık aşkta.", hint:"Sözcükler yer değiştirerek tekrarlanmış." },

  { cat:"anlam", answer:ART.TERDID, text:"Gül müdür, karanfil midir, nedir bu hâlin\nBilmem ki çözemedim ben bu bilmecenin.", hint:"Kararsızlık ve şüphe beklenmedik biçimde sonuçlanıyor." },
  { cat:"anlam", answer:ART.TERDID, text:"Sevinç midir, hüzün müdür, nedir bu gözyaşım\nAnlamadım, çözemedim.", hint:"Gözyaşının nedenini anlamlandırma çabası beklenmedik biçimde bırakılıyor." },

  { cat:"anlam", answer:ART.KATI, text:"Hayat ne garip bir oyun\nBazen güler, bazen ağlatır, ama\u2026", hint:"Söz yarıda kesilerek düşünce okuyucuya bırakılmış." },
  { cat:"anlam", answer:ART.KATI, text:"Bana derler gam yükünü çekme sen\nÇekerim elbet, ne yapayım bilmem ki\u2026", hint:"Söz yarıda kesilerek çaresizlik vurgulanmış." },

  { cat:"anlam", answer:ART.RUCU, text:"Dedim ki bir güle benziyor yanağın\nYok yok, goncadır açmamış daha.", hint:"İlk benzetmeden vazgeçip daha farklı bir benzetmeye geçiliyor." },
  { cat:"anlam", answer:ART.RUCU, text:"Sandım ki bir dost buldum kendime\nYok yok, sadece bir yalnızlık arkadaşıymış.", hint:"İlk yanılgıdan caynıp gerçeği görme." },

  { cat:"soz", answer:ART.SECI, text:"Yüzümde hüzün, içimde yangın, dilimde sitem.", hint:"Cümle sonlarında yapısal ses uyumu — düzyazı uyağı." },
  { cat:"soz", answer:ART.SECI, text:"Öyle olacak dünya kişiye hoşdâr olur\nUçtan uca gül ü gülzâr olur.", hint:"'Hoşdâr' ve 'gülzâr' ile cümle sonu uyak." },

  { cat:"anlam", answer:ART.TEKRIR, text:"Yine yandı canım, yine yandı\nAteşlere düştüm, yine yandı.", hint:"'Yine yandı' tekrarı acının sürekliliğini vurguluyor." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Sevda sevda dediler, sevdaya düştüm\nYandım yandım dediler, kül oldum.", hint:"'Sevda' ve 'yandım' tekrarı duygusal yoğunluğu artırıyor." },

  { cat:"anlam", answer:ART.ISTIFHAM, text:"Ne kaldı senden benden başka?", hint:"Soru yoluyla yalnızlık vurgulanıyor, cevap beklenmiyor." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Kim bilir ne kaldı geriye?", hint:"Soru yoluyla belirsizlik ifade ediliyor." },

  { cat:"anlam", answer:ART.NIDA, text:"Bre gâfil, uyan artık!", hint:"'Bre' ünlemiyle birine seslenme." },
  { cat:"anlam", answer:ART.NIDA, text:"Vay benim halime!", hint:"'Vay' ünlemiyle çaresizlik ifade ediliyor." },

  { cat:"soz", answer:ART.CINAS, text:"Benim gönlüm bir bahar\nBahar gelince açar güller.", hint:"'Bahar' hem gönlün durumu hem mevsim anlamında." },
  { cat:"soz", answer:ART.CINAS, text:"Canım yolunda toprak olaydım\nToprak olaydım da yoluna girseydim.", hint:"'Toprak' farklı anlamlarda kullanılmış." },

  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Aslan gibi kükredi Mehmetçik.", hint:"Mehmetçik aslana benzetilmiş, 'gibi' edatı kullanılmış." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Taş gibi kalbi vardı.", hint:"Kalbin duygusuzluğu taşa benzetilmiş." },

  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"O çınar gibiydi, kökleri derinde.", hint:"Yaşlı/tecrübeli kişi söylenmemiş, çınar söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Leylâ'yı aradım çöllerde.", hint:"Sevgili söylenmemiş, Leylâ (kendisine benzetilen) söylenmiş." },

  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Aşkın gözü kördür.", hint:"Aşk söylenmiş, ama neye benzetildiği (kör insan) söylenmemiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Yollar yorgun, adımlarım bitkin.", hint:"Yollar söylenmiş, insan söylenmemiş. Yorgunluk insani özellik." },

  { cat:"mecaz", answer:ART.TESHIS, text:"Kitaplar sessizce konuşuyordu raflarda.", hint:"Kitaplara konuşmak gibi insani özellik verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Artık dağlar sırtlarından kürklerini attılar\nOmuzlarına sislerden birer atkı atıyorlar.", hint:"Dağlara kürk çıkarma ve atkı atma gibi insani davranışlar verilmiş." },

  { cat:"anlam", answer:ART.MUBALAGA, text:"Aşkın ile serimden geçtim cihânı unuttum\nNe yâr kaldı ne ağyâr ne de bir nişâne kaldı.", hint:"Aşkla dünyayı ve her şeyi unutmak — abartma." },

  { cat:"soz", answer:ART.ALITERASYON, text:"Lalelerle lalezâr.", hint:"'L' sesinin tekrarıyla ses güzelliği yaratılmış." },
  { cat:"soz", answer:ART.ALITERASYON, text:"Fırtınalar koptu feleklerde.", hint:"'F' sesinin tekrarıyla ses ahengi." },

  { cat:"mecaz", answer:ART.KINAYE, text:"Etekleri zil çalıyordu.", hint:"Hem gerçek (eteklerin sallanması) hem mecaz (çok sevinmek). Asıl kastedilen mecaz." },

  { cat:"anlam", answer:ART.TENASUP, text:"Kalem, kâğıt, mürekkep hazırdı.", hint:"Yazı malzemeleri — aynı anlam alanına ait sözcükler bir arada." },
  { cat:"anlam", answer:ART.TENASUP, text:"Anne, baba, çocuk — aile saadeti.", hint:"Aileyi çağrıştıran sözcükler bir arada." },

  { cat:"anlam", answer:ART.TELMIH, text:"Kerem gibi yandım aşkınla.", hint:"Kerem ile Aslı hikâyesine gönderme." },
  { cat:"anlam", answer:ART.TELMIH, text:"Mevlânâ gibi sevdim seni.", hint:"Mevlânâ'nın aşk anlayışına gönderme." },

  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Müzeyyen oldu reyâhin bezendi bâğ-ı çemen\nMeğer ki haber geldi yârdan bu gece.", hint:"Bahçenin süslenmesi doğal; sevgiliden haber gelmesine bağlanmış." },

  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Sakla samanı gelir zamanı demişler.", hint:"Atasözü konuya uygun biçimde kullanılmış." },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Erken kalkan yol alır demişler.", hint:"Atasözü düşünceyi desteklemek için kullanılmış." },

  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Yürü bre zâlim dünya, sana gelmedik mi?", hint:"Yalın ama derin — kolay gibi görünüp benzeri zor söylenir." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Ne şair yaş döker ne âşık ağlar.", hint:"Sade ama güçlü ifade — sehl-i mümteni." },

  { cat:"anlam", answer:ART.TEZAT, text:"Doğru yalan iç içe.", hint:"Doğru ve yalan karşıt kavramlar bir arada." },
  { cat:"anlam", answer:ART.TEZAT, text:"İyi kötü ne varsa yaşadık.", hint:"İyi ve kötü zıt kavramlar bir arada." },

  { cat:"mecaz", answer:ART.INTAK, text:"Kuş dedi ki: 'Özgürlük benim kanatlarımda.'", hint:"Hayvan konuşturulmuş — intak." },
  { cat:"mecaz", answer:ART.INTAK, text:"Rüzgâr dedi ki: 'Ben her yere ulaşırım.'", hint:"Doğa varlığı konuşturulmuş." },

  { cat:"mecaz", answer:ART.TARIZ, text:"Ne kadar da çalışkansın, bütün gün uyudun!", hint:"Çalışkan olmadığı halde çalışkanmış gibi söyleyerek iğneleme." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Sen ne kadar da dürüstsün, her zaman yalan söylüyorsun!", hint:"Söylenenin tam tersi kastediliyor." },

  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Bu şiiri Orhan Veli'den dinledim.", hint:"Orhan Veli söylenerek onun şiiri/eseri kastedilmiş — sanatçı-yapıt ilgisi." },


  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Akşam, lekesiz, saf, iyi bir yüz gibi akşam.", hint:"Akşam yüze benzetilmiş. Edat: gibi, yön: lekesiz/saf. (Yahya Kemal)" },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Ah bu türküler, köy türküleri\nAna sütü gibi candan, ana sütü gibi temiz.", hint:"Türküler ana sütüne benzetilmiş. (Bedri Rahmi Eyüboğlu)" },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Kadife gibi yumuşak elleri vardı annemin.", hint:"Eller kadife'ye benzetilmiş; edat (gibi), yön (yumuşak)." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"İpek gibi ince saçlarını rüzgâra savurdu.", hint:"Saçlar ipeğe benzetilmiş; edat (gibi), yön (ince)." },
  { cat:"mecaz", answer:ART.TESBIH_TAM, text:"Deniz, ayna gibi dümdüz ve sakindi o sabah.", hint:"Deniz aynaya benzetilmiş; edat (gibi), yön (dümdüz/sakin)." },

  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Bu dil ağzımda annemin sütüdür.", hint:"Dil anne sütüne benzetilmiş; edat ve yön yok. (Yahya Kemal)" },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Salın da gel selvi boylum, salın da.", hint:"Boy selviye benzetilmiş; edat yok." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Yay kaşlarını çatma sevgilim.", hint:"Kaş yaya benzetilmiş; edat ve yön yok." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Mercan dudaklım, bir gül yüzlüm var benim.", hint:"Dudak mercana, yüz güle benzetilmiş; edat yok." },
  { cat:"mecaz", answer:ART.TESBIH_BELIG, text:"Gümüş bir dünya uyur tepelerde.", hint:"Ay ışığıyla aydınlanan manzara gümüşe benzetilmiş." },

  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Bir hilâl uğruna ya Rab ne güneşler batıyor.", hint:"Askerler (benzeyen) söylenmemiş, güneşler (kendisine benzetilen) söylenmiş. (Mehmet Akif)" },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"İki kapılı bir handa gidiyorum gündüz gece.", hint:"Dünya söylenmemiş, iki kapılı han söylenmiş. Doğum ve ölüm iki kapı." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Havada bir dost eli okşuyor tenimizi.", hint:"Rüzgâr söylenmemiş, dost eli söylenmiş." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"İçimdeki aslan uyandı artık.", hint:"Cesaret söylenmemiş, aslan söylenmiş." },

  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Çatma, kurban olayım, çehreni ey nazlı hilâl!", hint:"Hilâl söylenmiş, insan söylenmemiş. 'Çatma' insani özellik. (Mehmet Akif)" },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Toprak, çiçekleri bağrına bastı.", hint:"Toprak söylenmiş, anne söylenmemiş. 'Bağrına basma' insani özellik." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Dağ, başını bulutlara sokmuş uyukluyordu.", hint:"Dağ söylenmiş, insan söylenmemiş. Uyuklamak insani eylem." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Ağaçlar kollarını gökyüzüne açmış yalvarıyordu.", hint:"Ağaçlar söylenmiş, insan söylenmemiş. Yalvarmak insani." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Mehtap süzülerek indi bahçeye.", hint:"Mehtap söylenmiş, kuş söylenmemiş. Süzülerek inmek kuşa ait." },

  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Yaşar Kemal'i bir gecede bitirdim.", hint:"Sanatçı adı söylenerek eserleri kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Kalem kılıçtan keskindir.", hint:"Kalem→bilim/edebiyat, kılıç→askeri güç kastedilmiş — araç-amaç ilgisi." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Her yıl Mehmet Akif'i okuruz bu günlerde.", hint:"Şair söylenerek İstiklal Marşı/eserleri kastedilmiş." },
  { cat:"mecaz", answer:ART.MECAZI_MURSEL, text:"Batı bu soruna çözüm arıyor.", hint:"Yer adı söylenerek Batılı ülkeler/insanlar kastedilmiş." },

  { cat:"mecaz", answer:ART.KINAYE, text:"Hamama giren terler.", hint:"Gerçek: hamama giren terler. Mecaz: bir işe girişen sıkıntıya katlanır." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Burnu büyük insanlarla konuşmak zordur.", hint:"Gerçek: fiziksel büyüklük. Mecaz: kibirli. Asıl kastedilen mecaz." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Kulağı delik adamdır, onu aldatamazsın.", hint:"Gerçek: kulağında delik. Mecaz: uyanık, haberi olan. Kastedilen mecaz." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Turnayı gözünden vurdu bu sefer.", hint:"Gerçek: avda isabet. Mecaz: işi tam başardı. Kastedilen mecaz." },
  { cat:"mecaz", answer:ART.KINAYE, text:"Yakasız gömlekler bize\nFelek biçer demedim mi.", hint:"'Yakasız gömlek' hem gerçek (kefen) hem mecaz (ölüm). (Pir Sultan Abdal)" },

  { cat:"mecaz", answer:ART.TESHIS, text:"Yellerin kollarında uyudu çiçekler.", hint:"Yellere 'kol', çiçeklere 'uyumak' — insani özellikler." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Dağlar geçit vermedi bana.", hint:"Dağlara insani irade verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Ay, bulutların arkasından utanarak bakıyordu.", hint:"Aya 'utanmak' gibi insani duygu verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Dereler şarkı söylüyordu taşların arasında.", hint:"Derelere şarkı söylemek gibi insani yetenek verilmiş." },
  { cat:"mecaz", answer:ART.TESHIS, text:"Dertli dertli inliyordu keman.", hint:"Kemana dertli inlemek gibi insani özellik yüklenmiş." },

  { cat:"mecaz", answer:ART.INTAK, text:"Tilki: 'Ooo karga cenapları, ne kadar şirinsiniz!' dedi.", hint:"Tilki konuşturulmuş — fabllarda sık kullanılır. (La Fontaine)" },
  { cat:"mecaz", answer:ART.INTAK, text:"Karınca: 'Yazın çalışsaydın, kışın aç kalmazdın' dedi.", hint:"Karınca konuşturulmuş — fabl türünde intak." },
  { cat:"mecaz", answer:ART.INTAK, text:"Mum: 'Ben yanarım, kimse bilmez halimi' diye fısıldadı.", hint:"Cansız varlık konuşturulmuş — intak." },

  { cat:"mecaz", answer:ART.TARIZ, text:"Bize kâfir demiş müftü efendi\nTutalım ben ona diyem Müslüman\nVarıldıkta yarın rûz-ı cezâya\nİkimiz de çıkarız anda yalan.", hint:"Nef'i, 'Müslüman diyelim' diyerek aslında Müslümanlığını sorguluyor. (Nef'i)" },

  { cat:"anlam", answer:ART.TENASUP, text:"Suya versin bağban gülzârı zahmet çekmesin\nBir gül açılmaz yüzün tek verse bin gülzâre su.", hint:"Su, gülzâr, gül, bağban — bahçecilik temasında uyumlu sözcükler. (Fuzuli)" },
  { cat:"anlam", answer:ART.TENASUP, text:"Artık demir almak günü gelmişse zamandan\nMeçhule giden bir gemi kalkar bu limandan.", hint:"Demir almak, gemi, liman — denizcilik temasında uyumlu sözcükler. (Yahya Kemal)" },
  { cat:"anlam", answer:ART.TENASUP, text:"Arım balım peteğim\nGülüm dalım çiçeğim.", hint:"Arı, bal, petek\ngül, dal, çiçek — birbiriyle ilişkili sözcükler. (Karacaoğlan)" },

  { cat:"anlam", answer:ART.TEVRIYE, text:"Bâkî çemende hayli perîşan imiş varak\nBenzer ki bir şikâyeti var rûzgârdan.", hint:"'Rûzgâr' hem yel hem zaman/devir anlamında — iki gerçek anlam. (Bâkî)" },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Sordum nigârı dediler ahbâb\nSemt-i Vefâ'da doğru yoldadır.", hint:"'Vefâ' hem İstanbul'da semt hem sadakat anlamında. İki gerçek anlam." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Sarımsak da acı amma yemekte lâzım bir dişi.", hint:"'Dişi' hem sarımsak parçası hem kadın/dişi cins — iki gerçek anlam." },

  { cat:"anlam", answer:ART.TECAHUL, text:"Âb-ı gûndur günbed-i devvâr rengi bilmezem\nYâ muhît olmuş gözümden günbed-i devvâre su.", hint:"Fuzuli gökyüzünün rengini bilmezden gelir; belki gözyaşları kaplamıştır. (Fuzuli)" },
  { cat:"anlam", answer:ART.TECAHUL, text:"Melek misin yâ perîsin yâ rûh-ı kudsî aceb\nBu hüsn ile bu melâhat beşerede buluna mı?", hint:"Sevgilinin insan olduğunu bildiği halde melek mi peri mi diye sorar." },

  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Hâk-i pâyine yetem der ömrlerdir muttasıl\nBaşını taştan taşa vurup gezer âvâre su.", hint:"Suyun akışının nedeni yerçekimi; Fuzuli bunu Hz. Peygamber'in toprağına ulaşma arzusuna bağlar. (Fuzuli)" },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Lâlehadler yine gülşende neler etmediler\nServi yürütmediler goncayı söyletmediler.", hint:"Servinin sabit, goncanın sessiz olması doğal; şair bunu sevgili karşısında utanmaya bağlıyor. (Necâtî)" },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Kadir bilmeyenler almış eline\nOnun için boynun büker menekşe.", hint:"Menekşenin eğikliği doğal; kadir bilmeyenlere duyulan üzüntüye bağlanmış. (Karacaoğlan)" },

  { cat:"anlam", answer:ART.TEZAT, text:"Aşk derdiyle hoşem el çek ilacımdan tabîb\nKılma derman ki helâkim zehri dermânındadır.", hint:"Dert-derman, zehir-ilaç zıt kavramları bir arada. (Fuzuli)" },
  { cat:"anlam", answer:ART.TEZAT, text:"Ne efsûnkâr imişsin âh ey didâr-ı hürriyet\nEsîr-i aşkın olduk gerçi kurtulduk esâretten.", hint:"Hürriyet-esaret, esir olmak-kurtulmak zıt kavramlar. (Namık Kemal)" },
  { cat:"anlam", answer:ART.TEZAT, text:"Ne siyâh eylemiş bu nâsiyeyi\nSaçımı bembeyaz eden bahtım.", hint:"Siyah-bembeyaz zıt kavramlar. (Abdülhak Hamid)" },

  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Bârân değil şafak değil ebr-i seher değil\nGözyaşıdır ciğer kanıdır dûd-ı âhdır.", hint:"Bârân→gözyaşı, şafak→ciğer kanı, ebr→dûd-ı âh sıralı eşleştirme." },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Sakın bir söz söyleme yüzüme bakma sakın\nSesini duyan olur sana göz koyan olur.", hint:"Söz→ses duymak, bakma→göz koymak sıralı eşleştirme. (Faruk Nafiz)" },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Bâğ-ı dehrin hem hazânın hem bahârın görmüşüz\nBiz neşâtın da gamın da rûzgârın görmüşüz.", hint:"Hazân→gam, bahâr→neşât sıralı eşleştirme. (Nâbî)" },

  { cat:"anlam", answer:ART.TELMIH, text:"Leylâ gelin oldu Mecnun mezarda\nBir susuz yolcu yok şimdi dağlarda.", hint:"Leylâ ile Mecnun hikâyesine telmih. (Faruk Nafiz)" },
  { cat:"anlam", answer:ART.TELMIH, text:"Mende Mecnûn'dan füzûn âşıklık isti'dâdı var\nÂşık-ı sâdık benim Mecnûn'un ancak adı var.", hint:"Mecnun'un aşkına telmih. (Fuzuli)" },
  { cat:"anlam", answer:ART.TELMIH, text:"Gönlünü Şîrîn'in aşkı sarınca\nO hızla dağları Ferhâd yarınca.", hint:"Ferhat ile Şirin hikâyesine telmih. (Faruk Nafiz)" },
  { cat:"anlam", answer:ART.TELMIH, text:"Süleyman kuş dili bilir dediler\nSüleyman var Süleyman'dan içeri.", hint:"Hz. Süleyman'ın kuş dili bilmesine telmih. (Yunus Emre)" },

  { cat:"anlam", answer:ART.MUBALAGA, text:"Merkez-i hâke atsalar da bizi\nKürre-i arzı patlatır çıkarız.", hint:"Yerin merkezine atılsa bile dünyayı patlatıp çıkmak — abartma. (Namık Kemal)" },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Şühedâ fışkıracak toprağı sıksan şühedâ.", hint:"Toprağı sıkınca şehitlerin fışkırması — abartma. (Mehmet Akif)" },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Bir gün doludizgin boşanan atlarımızla\nYerden yedi kat Arş'a kanatlandık o hızla.", hint:"Atların Arş'a kanatlanması — abartma. (Yahya Kemal)" },

  { cat:"anlam", answer:ART.TEKRIR, text:"Bu yağmur, bu yağmur, bu kıldan ince\nÖpüşten yumuşak yağan bu yağmur.", hint:"'Bu yağmur' tekrarıyla ahenk ve anlam güçlendirilmiş. (Necip Fazıl)" },
  { cat:"anlam", answer:ART.TEKRIR, text:"Söz ola kese savaşı, söz ola kestire başı\nSöz ola ağulu aşı bal ile yağ ede bir söz.", hint:"'Söz ola' tekrarıyla sözün gücü vurgulanmış. (Yunus Emre)" },
  { cat:"anlam", answer:ART.TEKRIR, text:"Kimsesizim kimsem yoktur herkesin var kimsesi\nKimsesiz kaldım meded kıl kimsesizler kimsesi.", hint:"'Kimsesiz/kimse' tekrarıyla yalnızlık vurgulanmış." },

  { cat:"anlam", answer:ART.NIDA, text:"Ey bu topraklar için toprağa düşmüş asker\nGökten ecdât inerek öpse o pâk alnı değer.", hint:"'Ey' ünlemiyle şehitlere seslenme. (Mehmet Akif)" },
  { cat:"anlam", answer:ART.NIDA, text:"Eyvâh! Beş on kâfirin îmânına kandık.", hint:"'Eyvâh' ünlemiyle pişmanlık ifade ediliyor." },

  { cat:"anlam", answer:ART.ISTIFHAM, text:"Hangi çılgın bana zincir vuracakmış şaşarım!", hint:"'Hangi' soru sözcüğüyle cevap beklenmeksizin istifham. (Mehmet Akif)" },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Ağlasam sesimi duyar mısınız\nMısralarımda gözyaşı olsa?", hint:"Cevap beklenmeden soru biçiminde duygu aktarılmış. (Cahit Sıtkı Tarancı)" },

  { cat:"anlam", answer:ART.RUCU, text:"Zaman gelir ki cihân içre ins ü cân kalmaz\nDeğil değil yalınız ins ü cân, cihân kalmaz.", hint:"Önce 'insanlar kalmaz' der, sonra caynıp 'dünya da kalmaz' diyerek güçlendirir." },
  { cat:"anlam", answer:ART.RUCU, text:"Kaddin libâs-ı sürh ile âfet değil midir\nÂfet değil kızılca kıyâmet değil midir.", hint:"'Afet' der, caynıp 'kızılca kıyamet' ile güçlendirir." },

  { cat:"anlam", answer:ART.TERDID, text:"En ağır işçi benim\nGün yirmi dört saat\nSeni düşünüyorum.", hint:"'En ağır işçi' ile fiziksel iş beklenirken 'seni düşünüyorum' şaşırtır. (Ümit Yaşar)" },

  { cat:"anlam", answer:ART.AKIS, text:"Didem rûhunu gözler, gözler rûhunu didem\nKıblem olalı kaşın, kaşın olalı kıblem.", hint:"Didem-gözler\ngözler-didem ters çevrilmiş. (Nazmî)" },
  { cat:"anlam", answer:ART.AKIS, text:"Utandım ağlayarak, ağladım utanmayarak.", hint:"Utandım-ağlayarak\nağladım-utanmayarak çaprazlanmış. (Mehmet Akif)" },
  { cat:"anlam", answer:ART.AKIS, text:"Her inişin bir yokuşu, her yokuşun bir inişi vardır.", hint:"İniş-yokuş\nyokuş-iniş yer değiştirmiş." },

  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Söz ola kese savaşı, söz ola kestire başı.", hint:"Sade kelimelerle derin anlam — taklidi zor. (Yunus Emre)" },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Âşık-ı sâdık benim Mecnûn'un ancak adı var.", hint:"Kısa ve yalın ama derin — benzeri söylenemez. (Fuzuli)" },

  { cat:"anlam", answer:ART.KATI, text:"Bu şehirde yalnızım\nBir tren sesi duydum mu iki gözüm iki çeşme\nÇünkü\u2026", hint:"Ağlamanın sebebi söylenmeden söz kesilmiş. (Orhan Veli)" },

  { cat:"soz", answer:ART.CINAS, text:"Bir güzel şûha dedim iki gözün sürmelidir\nDedi vallahi seni Hind'e kadar sürmelidir.", hint:"İlk 'sürmeli' göze sürme çekilmiş, ikincisi sürgün etmek anlamında." },
  { cat:"soz", answer:ART.CINAS, text:"Böyle bağlar yâr başın böyle bağlar.", hint:"İlk 'bağlar' bahçe, ikinci 'bağlar' bağlamak fiili." },
  { cat:"soz", answer:ART.CINAS, text:"Eyleme vaktini zâyi deme kış, yaz oku yaz.", hint:"İlk 'yaz' mevsim, ikinci 'yaz' yazmak fiilinin emir kipi." },
  { cat:"soz", answer:ART.CINAS, text:"Niçin kondun a bülbül kapımdaki asmaya\nBen yârimden ayrılmam götürseler asmaya.", hint:"İlk 'asma' bitki, ikinci 'asma' idam etmek." },

  { cat:"soz", answer:ART.ALITERASYON, text:"Seherlerde seyre koyuldum semâyı, sahrâyı.", hint:"'S' sesinin tekrarıyla ses ahengi. (Tevfik Fikret)" },
  { cat:"soz", answer:ART.ALITERASYON, text:"Sokaktayım, kimsesiz bir sokak ortasında.", hint:"'S' ve 'k' seslerinin tekrarıyla aliterasyon. (Necip Fazıl)" },
  { cat:"soz", answer:ART.ALITERASYON, text:"Kara toprak içinde kara karıncayı karanlık gecede görür.", hint:"'K' ve 'r' seslerinin yoğun tekrarıyla aliterasyon." },

  { cat:"soz", answer:ART.SECI, text:"Ey gözlerin nuru, gönüllerin sürûru; başımızın tâcı, dil ehlinin mîrâcı.", hint:"Nuru-sürûru, tâcı-mîrâcı — düzyazıda iç uyak." },
  { cat:"soz", answer:ART.SECI, text:"Gönüller sultanı, dertlilerin lokmanı, âşıkların dermanı.", hint:"Sultanı-lokmanı-dermanı '-anı' uyumuyla seci." },

  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Allah'a sığın şahs-ı halîmin gazabından\nZîrâ yumuşak huylu atın çiftesi pektir.", hint:"'Yumuşak huylu atın çiftesi pektir' atasözü kullanılmış. (Ziya Paşa)" },
  { cat:"soz", answer:ART.IRSAL_I_MESEL, text:"Bed-asla necâbet mi verir hiç üniforma\nEşek ölse de eşektir altın semer vursan da.", hint:"'Eşeğe altın semer vursan da eşektir' atasözü ile düşünce pekiştirilmiş. (Ziya Paşa)" },

  { cat:"mecaz", answer:ART.TESHIS, text:"Bahçedeki çiçekler ona el salladı.", hint:"Çiçeklere el sallamak gibi insani davranış verilmiş." },
  { cat:"mecaz", answer:ART.KAPALI_ISTIARE, text:"Bir çocuk ağlıyor içimde.", hint:"İçteki hüzünlü hal söylenmiş, çocuğa (kendisine benzetilen) benzetilmiş ama çocuk söylenmemiş." },
  { cat:"anlam", answer:ART.MUBALAGA, text:"Gül yüzünü görüp şevk ile bağrıma basam\nSanki cennet bana lutfetti Hudâ-yı Kâdir.", hint:"Sevgilinin yüzünü bağrına basınca cenneti yaşamak — abartma." },
  { cat:"anlam", answer:ART.TEKRIR, text:"Benim gönlüm bir deli kuş\nUçar durur daldan dala\nBenim gönlüm bir deli kuş\nKonar durur yâre yâre.", hint:"'Benim gönlüm bir deli kuş' tekrarıyla duygu pekiştirilmiş." },
  { cat:"soz", answer:ART.CINAS, text:"Benim bu derdime deva bulunmaz\nDeva bulunsa da dermanım olmaz.", hint:"'Deva' ve 'derman' benzer sesli ama farklı bağlamlarda." },
  { cat:"anlam", answer:ART.HUSNI_TALIL, text:"Ay, senin güzelliğini kıskanıp bulutların ardına gizlendi.", hint:"Ayın bulutla kapanması doğal; sevgilinin güzelliğine kıskanmaya bağlanmış." },
  { cat:"mecaz", answer:ART.ACIK_ISTIARE, text:"Yıldızlar şahit olsun aşkıma.", hint:"Sevgili/tanrı söylenmemiş, yıldızlar (kendisine benzetilen) söylenmiş." },

  { cat:"anlam", answer:ART.RUCU, text:"Ne mümkün zulm ile bîdâd ile imhâ-yı hürriyet\nDeğil mümkün, değil ey düşmen-i devlet, değil mümkün.", hint:"Hürriyetin yok edilemeyeceği söylenip, 'değil mümkün' tekrarıyla cayarak güçlendiriliyor. (Namık Kemal)" },
  { cat:"anlam", answer:ART.RUCU, text:"Gerçi güzel değildir bence ölmek\nFakat yaşamak da o kadar güzel değil.", hint:"Ölmenin güzel olmadığı söylenip, yaşamanın da güzel olmadığı eklenerek ilk yargıdan kısmen caynılıyor." },
  { cat:"anlam", answer:ART.RUCU, text:"Bana mı düşmüş seni kurtarmak ey dünya\nBelki de düşmüş, ne çıkar.", hint:"İlk cümlede sorgulanıp ikincide caynılarak kabul ediliyor." },
  { cat:"anlam", answer:ART.TERDID, text:"Bir gün bir kitapta okudum ki\nBütün insanlar kardeştir.", hint:"Sıradan bir kitap okuma anlatılırken 'bütün insanlar kardeştir' ile beklenmedik bir derinlik yaratılıyor." },
  { cat:"anlam", answer:ART.TERDID, text:"Ben ki her nisan bir yaş daha genç\nSen ki her eylül bir yaprak kadar sarı.", hint:"Nisanda gençleşmek ve eylülde sararmak karşıtlığı beklenmedik biçimde sonuçlanıyor." },
  { cat:"anlam", answer:ART.KATI, text:"Ben sana küskünüm aslında,\nKızgınım,\nBelki de\u2026", hint:"Duygular ifade edilirken birden duraksanıp söz tamamlanmıyor." },
  { cat:"anlam", answer:ART.KATI, text:"Sana bir sır vereyim mi?\nAslında\u2026", hint:"Sır verileceği söylenip açıklanmadan söz kesiliyor." },
  { cat:"anlam", answer:ART.KATI, text:"Dün gece rüyamda seni\u2026", hint:"Rüyada ne görüldüğü söylenmeden söz kesiliyor." },
  { cat:"anlam", answer:ART.KATI, text:"Seni ne kadar sevdiğimi bilsen\u2026", hint:"Sevginin büyüklüğü ifade edilecekken söz kesiliyor." },
  { cat:"anlam", answer:ART.AKIS, text:"Nefsindir sana düşman, sen nefsine düşman ol.", hint:"Düşman kelimesiyle özne ve nesne yer değiştirilerek akis yapılmış." },
  { cat:"anlam", answer:ART.AKIS, text:"Yaşamak ölmek değil, ölmek yaşamaktır bazen.", hint:"Yaşamak ve ölmek ters çevrilerek farklı bir bakış sunuluyor." },
  { cat:"anlam", answer:ART.AKIS, text:"Gamdan âzâde değil âşık-ı dil-haste bugün\nÂşık-ı dil-haste değil gamdan âzâde bugün.", hint:"Dizelerdeki kavramlar ters çevrilerek akis yapılmış." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Ben giderim adım kalır\nDostlar beni hatırlasın.", hint:"Yunus Emre'nin basit gibi görünen ama derin anlamlı, benzeri söylenemez dizeleri." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Aşk imiş her ne var âlemde\nİlm bir kıyl ü kâl imiş ancak.", hint:"Fuzuli'nin sade ama derin dizeleri — aşkın ilimden üstünlüğü. Benzeri söylenemez." },
  { cat:"soz", answer:ART.SECI, text:"Söz odur ki ola gönlüne ferah, cisme selâh.", hint:"'Ferah' ve 'selâh' ile cümle sonunda ses uyumu — düzyazı kafiyesi." },
  { cat:"soz", answer:ART.SECI, text:"İyilik eden iyilik bulur, kötülük eden kötülük bulur.", hint:"'Bulur' tekrarıyla cümle sonlarında uyak — seci." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Bunca gamı yüklenip nereye gidersin?", hint:"Cevap beklemeden çaresizlik ve duygu ifade ediliyor." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Ne kaldı senden geri, ey koca ömür?", hint:"Ömrün sonunda yaşanan pişmanlık soru yoluyla aktarılıyor." },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Daha ne kadar bekleyeceğim?", hint:"Sabırsızlık ve çaresizlik soru yoluyla ifade ediliyor." },
  { cat:"mecaz", answer:ART.TARIZ, text:"Çok mütevazısın, sürekli kendini övüyorsun!", hint:"Söylenenin (mütevazı) tam tersi (kibirli) kastedilerek iğneleme yapılıyor." },

  { cat:"anlam", answer:ART.TENASUP, text:"Lâleyi sümbülü gülü hâr almış\nZevk u şevk ehlini âh u zâr almış.", hint:"Lâle, sümbül, gül, hâr (bitki) ve zevk, şevk, âh, zâr (duygu) — iki ayrı anlam alanında tenasüp." },
  { cat:"anlam", answer:ART.TENASUP, text:"Aramazdık gece mehtâbı yüzün parlarken\nBir uzak yıldıza benzerdi güneş sen varken.", hint:"Gece, mehtâb, yıldız, güneş — gök cisimleri arasında tenasüp. (Faruk Nafiz)" },
  { cat:"anlam", answer:ART.TENASUP, text:"Mest oluptur çeşm ü ebrûnun hayâlinde imam\nOkumaz mihrâbda bir harf-i Kur'ân'ı dürüst.", hint:"İmam, mihrâb, Kur'ân — dinî kavramlar arasında tenasüp. (Fuzuli)" },
  { cat:"anlam", answer:ART.TENASUP, text:"Câmlar şikest olmuş meyler dökülmüş\nSâkîler meclisten çekmiş ayağı.", hint:"Câm, mey, sâkî, meclis — içki meclisi kavramları arasında tenasüp." },
  { cat:"anlam", answer:ART.TENASUP, text:"Aşk derdiyle hoşem el çek ilâcımdan tabîb\nKılma derman kim helâkim zehri dermânındadır.", hint:"Dert, ilâç, tabîb, derman, zehir — tıp alanından sözcüklerle tenasüp. (Fuzuli)" },
  { cat:"anlam", answer:ART.TEKRIR, text:"Sahil seni rüzgâr seni akşam seni bekler.", hint:"'Seni' sözcüğünün üç kez tekrarı özlemi pekiştiriyor. (Faruk Nafiz)" },
  { cat:"anlam", answer:ART.TEKRIR, text:"Akşam yine akşam yine akşam\nGöllerde bu dem bir kamış olsam.", hint:"'Akşam' sözcüğünün üç kez tekrarı hüzünlü ahenk yaratıyor. (Ahmet Haşim)" },
  { cat:"anlam", answer:ART.TEKRIR, text:"Kapalı Çarşı içinde kapalı rüya çarşıları\nKapalı Çarşı içinde öfke ve af çarşıları.", hint:"'Kapalı Çarşı' tekrarı mekânın gizemini pekiştiriyor. (Sezai Karakoç)" },
  { cat:"mecaz", answer:ART.INTAK, text:"Benim adım dertli dolap\nSuyum akar yalap yalap\nDerdim vardır inilerim\nDönme dolap dönme dolap.", hint:"Su dolabı kendi ağzından konuşarak derdini anlatıyor — halk edebiyatı." },
  { cat:"mecaz", answer:ART.INTAK, text:"Sarı tanbur benim adım\nArşa çıkıyor feryadım\nPir Sultan'ımdır üstadım\nBen anınçin inilerim.", hint:"Tambur kendi ağzından konuşuyor. (Pir Sultan Abdal)" },
  { cat:"mecaz", answer:ART.INTAK, text:"Ol ulu katına bu miskîn har\nVardı yüz sürdü didi ey server.", hint:"Eşek konuşturulmuş — Türk edebiyatının ilk fabli. (Şeyhî, Harnâme)" },
  { cat:"soz", answer:ART.ALITERASYON, text:"Dağlar ağarırken konuşurduk tepelerde\nYüzlerce serin parça bulutlar yüzerdi.", hint:"'R' sesinin tekrarı (dağlar, ağarırken, konuşurduk, tepelerde, serin, parça, yüzerdi) akıcılık sağlıyor. (Yahya Kemal)" },
  { cat:"soz", answer:ART.ALITERASYON, text:"Açıl bâğun gül ü nesrîni ol ruhsârı görsünler\nSalın serv ü sanavber şîve-i reftârı görsünler.", hint:"'S' ve 'r' seslerinin tekrarıyla zarif ahenk yaratılmış. (Bâkî)" },

  { cat:"anlam", answer:ART.RUCU, text:"Makber değil bir türbe\nTürbe değil bir mâbed\nMâbed değil bir küre\nKüre değil bir fezâ-yı bî-intihâ olmalıydı.", hint:"Her cayışta daha güçlü bir ifadeye ulaşılıyor — mezardan sonsuz fezaya. (Abdülhak Hamid)" },
  { cat:"anlam", answer:ART.RUCU, text:"Öyle bir devr-i zamân gelir ki ins ü cin kalmaz\nYok ins ü cin değil dünyâ da kalmaz.", hint:"Önce 'insanlar kalmaz' der, caynıp 'dünya da kalmaz' diyerek güçlendirir." },
  { cat:"anlam", answer:ART.RUCU, text:"Gün görmedim bu dengesiz dünyâda\nYok yok gün gördüm ama\nBozbulanık günler gördüm.", hint:"'Gün görmedim' der, cayar, gördüğü günlerin bozbulanık olduğunu söyleyerek pekiştirir. (Metin Altıok)" },
  { cat:"anlam", answer:ART.TERDID, text:"Görünce uzanmış yâr kucağına\nBoynunu dolamış zülfü bağına\nKurşunu kahpeye atacağına\nKendine çevirdin... Aman be Ali!", hint:"Ali'nin sevgilisini vuracağı beklenir, kendini vurduğu ortaya çıkar. (Faruk Nafiz, Ali)" },
  { cat:"anlam", answer:ART.TERDID, text:"Uzayacağa benzer\nTutuştuğumuz lâdes\nBak kaç sene geçti\nAldatamadın beni\nÖlüm kardeş!", hint:"Muhatabın ölüm olduğu son dizeye kadar belirsiz. (Behçet Necatigil)" },
  { cat:"anlam", answer:ART.TERDID, text:"İşte su\nİşte ışık\nİşte hava\nİşte Dursun bebek bizim dünya.", hint:"Su, ışık, hava sıralanır — son dizede yeni doğan bebeğe dünya tanıtılır. (Melih Cevdet Anday)" },
  { cat:"anlam", answer:ART.KATI, text:"Garibim\nNe bir güzel var avutacak gönlümü\nBu şehirde\nBir tren sesi duymaya göreyim\nİki gözüm iki çeşme\u2026", hint:"Neden ağladığını söylemez, sözü keser. (Orhan Veli)" },
  { cat:"anlam", answer:ART.KATI, text:"Ey kimsesiz âvâre çocuklar!\nHele sizler!\nHele sizler\u2026", hint:"Ne söyleyeceğini bitiremeden keser, okuyucuyu vicdanıyla baş başa bırakır. (Tevfik Fikret)" },
  { cat:"anlam", answer:ART.KATI, text:"Nasıl nasıl size derdimi\u2026\nBir dert ki düşman başına\u2026", hint:"Derdini anlatamaz, sözü keser. (Orhan Veli)" },
  { cat:"anlam", answer:ART.AKIS, text:"Oddan su çıkardın\nSudan od çıkardın.", hint:"'Od-su' ve 'su-od' yer değiştirilerek akis yapılmış. (Fuzuli)" },
  { cat:"anlam", answer:ART.AKIS, text:"Gül diken olmaz u diken gül olmaz\nBunların her birinin aslı başka.", hint:"'Gül-diken' ve 'diken-gül' ters çevrilerek akis. (Fuzuli)" },
  { cat:"anlam", answer:ART.AKIS, text:"Her kemâlin bir zevâli\nHer zevâlin bir kemâli vardır.", hint:"'Kemâl-zevâl' çifti yer değiştirilerek akis — her olgunluğun bir çöküşü var." },
  { cat:"anlam", answer:ART.AKIS, text:"Bilmem nic'olur hâlim\nHâlim nic'olur bilmem.", hint:"'Bilmem' ve 'hâlim' yer değiştirerek tam akis." },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Gâh çıkarım gökyüzüne seyrederim âlemi\nGâh inerim yeryüzüne seyreder âlem beni.", hint:"Sade dille evrensel hakikat — kolay gibi ama taklidi zor. (Yunus Emre)" },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Ders-i aşkın müşkilin Yahyâ nice halleylesin\nSöyleyenler kendini bilmez bilenler söylemez.", hint:"Aşkın paradoksu sade dille — kolay görünür ama benzeri söylenemez. (Şeyhülislâm Yahyâ)" },
  { cat:"anlam", answer:ART.SEHLI_MUMTENI, text:"Ben ki toz kanatlı bir kelebeğim\nMinicik gövdeme yüklü Kafdağı.", hint:"İnsanın varoluş yükü sade kelimelerle — sehl-i mümteni. (Necip Fazıl)" },
  { cat:"soz", answer:ART.SECI, text:"İlâhi gönlüm oduna ne yaktınsa o tüter\nİlâhi vücudum bahçesine ne diktinse o biter.", hint:"'Yaktınsa-diktinse' ve 'tüter-biter' arasında seci uyumu. (Sinan Paşa)" },
  { cat:"soz", answer:ART.SECI, text:"Dost yolunda nistlik gerek\nYâr önünde pestlik gerek\nTen cübbesi çâk gerek\nGönül evi pâk gerek.", hint:"'Nistlik-pestlik' ve 'çâk-pâk' arasında seci uyumu." },
  { cat:"soz", answer:ART.SECI, text:"Işk iledür gögün döndügi\nIşk iledür yirün turduğı\nIşkdur çarha koyan felegi\nIşkdur temcîd okudan melegi.", hint:"'Döndügi-turduğı' ve 'felegi-melegi' arasında seci. (Sinan Paşa)" },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Nedir bu handeler bu işveler bu nâz u istiğnâ\nNedir bu cilveler bu şîveler bu kâmet-i bâlâ.", hint:"Sevgilinin güzelliğini soru biçiminde anlatır, cevap beklemez. (Bâkî)" },
  { cat:"anlam", answer:ART.ISTIFHAM, text:"Olur mu dünyaya indirsem kepenk\nGözyaşı döksem Nuh Tufanı'na denk.", hint:"Acının büyüklüğü soru biçiminde — cevap beklenmez. (Necip Fazıl)" },
  { cat:"mecaz", answer:ART.TARIZ, text:"Vermedi ablukada şân-ı donanmaya halel\nİngiliz devletine olsa sezâdır amiral.", hint:"Osmanlı amiralini över gibi görünür ama donanmayı hiç kullanmadığını iğneler. (Ziya Paşa)" },
  { cat:"mecaz", answer:ART.TARIZ, text:"Üç parmak noksan ölç ölçersen kile\nDört kuruşa sekiz kuruş kat hile\nKomşunun evini yakarsan yanma.", hint:"Hırsızlık ve hileyi öğütler gibi anlatır, tam tersini kasteder. (Huzurî)" },
  { cat:"mecaz", answer:ART.TARIZ, text:"Şu kavga bitse dersin\nAcıkmasam dersin\nUykum gelmese dersin\nÖlem desene.", hint:"Tembelin şikâyetlerini sıralayarak iğneler. (Orhan Veli)" },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Bir bûse mi bir gül mü verirsin dedi gönlüm\nBir nîm tebessümle o âfet gülüverdi.", hint:"'Gülüverdi' hem güldü (tebessüm) hem gül verdi (çiçek) — iki gerçek anlam." },
  { cat:"anlam", answer:ART.TEVRIYE, text:"Minnet Hudâ'ya devlet-i dünyâ fenâ bulur\nBâkî kalır sahîfe-i âlemde adımız.", hint:"'Bâkî' hem kalıcı/ebedî hem şairin mahlası — iki gerçek anlam. (Bâkî)" },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Fikr-i zülfün dilde tâb-ı sûz-ı aşkın sînede\nNârdır külhanda gûyâ mârdır gencînede.", hint:"Zülf→mâr (yılan), aşk ateşi→nâr (ateş) — çapraz eşleştirme. (Nef'i)" },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"İçimde kor donar buzlar çözülür\nYağan ateş midir kar mıdır bilmem.", hint:"Kor→ateş, buz→kar sıralı eşleştirme. (Behçet Necatigil)" },
  { cat:"anlam", answer:ART.LEFF_U_NESR, text:"Sen bana en sâdık bir arkadaştın\nGönlümde ateştin gözümde yaştın\nNe diye tutuştun ne diye taştın.", hint:"Ateş→tutuşmak, yaş→taşmak sıralı eşleştirme." },
  { cat:"anlam", answer:ART.NIDA, text:"Ey şehîd oğlu şehîd isteme benden makber\nSana âgûşunu açmış duruyor Peygamber.", hint:"Şehitlere 'ey' ile seslenme — derin saygı ve hüzün. (Mehmet Akif)" },
  { cat:"anlam", answer:ART.NIDA, text:"Bu son fasıldır ey ömrüm nasıl geçersen geç.", hint:"Kendi ömrüne 'ey ömrüm' diye seslenerek kabulleniş ve hüzün. (Yahya Kemal)" },
  { cat:"anlam", answer:ART.NIDA, text:"Ey köyleri hududa bağlayan yaşlı yollar\nAğır kağnılarla medrese gören köylüler.", hint:"Anadolu yollarına 'ey' ile duygusal seslenme. (Faruk Nafiz)" },
  { cat:"anlam", answer:ART.NIDA, text:"Ey sahn-ı mezâlim evet ey sahne-i garrâ\nEy sahne-i zî-şa'şaa-i dûd-ı muannid.", hint:"İstanbul'a öfke ve sitemle art arda 'ey' ile seslenme. (Tevfik Fikret, Sis)" },
]);
